### ISSUE TITLE
Initial Main Page Wire Frame Mobile

### ISSUE THREAD

**Issue by eugenemonnier** [MoviesNow/MoviesNowApp#1]
As a user, when I visit the “Home” page on my mobile device, I would want to see a page that has a visually appealing page layout.

**Feature Tasks**
- [x] Mobile display size is 414px W x 896px H
- [x] Main page has a basic wire frame body
  - [x] Top of the body contains 2 text box input fields with labels and a H1 centered between "MoviesNOW"
  - [x] Add 6 placeholder images using grid or flex
  - [x] Form section contains all text boxes and movie images
- [x] Main page has a basic wire frame footer
  - [x] Footer has fixed positioning at the bottom of the page. 
  - [x] Footer has 3 buttons properly spaced and sized.
**Acceptance Tests**
- [x] All block elements of art boarded Main wire frame show correctly when page loads.

**Comment by cindyweiss** [comment]
https://github.com/MoviesNow/MoviesNowApp/pull/18
completed all designer requirements on css
