### ISSUE TITLE
Create tables in schema.sql

### ISSUE THREAD

**Issue by eugenemonnier** [MoviesNow/MoviesNowApp#12]
As a user, I want fast reliable results from the web app.

### Feature Tasks
- [x] Locally, create sql database movies_now
- [x] Start schema.sql by dropping all 3 tables if they exist.
- [x] Create movies table in schema.sql with the following columns names and data types
  - [x] title VARCHAR (255)
  - [x] description VARCHAR
  - [x] ratings_code VARCHAR (255)
  - [x] img_url VARCHAR (255)
  - [x] runtime VARCHAR (255)
- [x] Create search_results table in schema.sql with the following columns
  - [x] title VARCHAR (255)
  - [x] theater VARCHAR (255)
  - [x] date_time TIMESTAMP
  - [x] expire_date_time TIMESTAMP
- [x] Create users table in schema.sql with the following columns
  - [x] username VARCHAR (255)
  - [x] firstname VARCHAR (255)
  - [x] lastname VARCHAR (255)
  - [x] email VARCHAR (255)

### Acceptance Tasks
- In console run `psql -f sql/schema.sql -d movies_now`
  - [x] First time running you should see that the drop tables portion gets skipped as the tables do not yet exist.
- In console run `psql`
- In psql run `\c movies_now`
  - [x] You should see the message "You are now connected to database "movies_now" as user "`<your username here>`"
- Now run in psql `SELECT * FROM movies;`
  - [x] You should see an empty table with all of the columns listed above
- Now run in psql `SELECT * FROM search_results;`
  - [x] You should see an empty table with all of the columns listed above
- Now run in psql `SELECT * FROM users;`
  - [x] You should see an empty table with all of the columns listed above

**Comment by Blandine12** [comment]
I have some issues seeing tables when I get to SELECT * From, I might be doing something wrong.

**Comment by Blandine12** [comment]
https://github.com/MoviesNow/MoviesNowApp/pull/16
