### ISSUE TITLE
Initial About Page Wire Frame for Mobile

### ISSUE THREAD

**Issue by eugenemonnier** [MoviesNow/MoviesNowApp#17]
As a user, when I visit the “About” page on my mobile device, I would want to see a page that has a visually appealing page layout.

**Feature Tasks**
- [x] Create about.ejs in views folder 
- [x] Mobile display size is 414px W x 896px H
- [x] About page has a header with only the title centered (make this under header.ejs and add it to the about.ejs) 
- [x] About page has a basic wire frame for main
  - [x] About page has large container div pictured. 
  - [x] Inside that div add a H1 and then 3 place holder images
- [x] Main page has a basic wire frame footer 
  - [x] Build footer under footer.ejs
  - [x] Footer has fixed positioning at the bottom of the page. 
  - [x] Footer has 2 buttons properly spaced and sized.
**Acceptance Tests**
- [x] All block elements of art boarded About wire frame show correctly when page loads.

**Comment by Blandine12** [comment]
https://github.com/MoviesNow/MoviesNowApp/pull/20
