### ISSUE TITLE
Setup Basic File Structure

### ISSUE THREAD

**Issue by eugenemonnier** [MoviesNow/MoviesNowApp#5]
As a user, I want my application to load quickly so that I have an enjoyable experience.

### Description
**Given** that the user opens the application in a browser
**When** the user navigates to the home page
**Then** the index should load.

### Feature Tasks

- [x] Create the following file structure.
```
├── README.md
├── package-lock.json
├── package.json
├── server
│   ├── database.js
│   ├── middleware.js
│   ├── routes.js
│   ├── server.js
│   └── views
│       └── index.ejs
├── sql
│   └── schema.sql
└── www
    ├── css
    │   ├── base.css
    │   ├── layout.css
    │   ├── modules.css
    │   └── reset.css
    └── js
        └── app.js
```
Acceptance Test:
- [x] Run "ls" command on terminal inside of repository and check that all files are present.

**Comment by cindyweiss** [comment]
set up the sql and server.js files
